### PR TITLE
Creating dockerfile for frontend and backend

### PR DESCRIPTION
**Pull request by Kalpesh-18**
Execute the following commands in order

1. docker build --file=frontend.dockerfile  -t password-web-frontend .
2. docker build --file=backend.dockerfile  -t password-web-backend .
3. docker-compose -f docker-compose.yml up

Check localhost:8000

image

### CODE REVIEW

**Comment by Kalpesh-18** [comment]
Hey I just noticed the failure and went through the logs, just wanted to know if the build is using the created dockerfiles?

**Comment by 7ubi** [comment]
No it's for Django Unit Tests for them to run you need to add a Secret Key in the Github Settings
image

**Comment by Kalpesh-18** [comment]
I should add the secret key from .env file right?

**Comment by 7ubi** [comment]
I don't think the value really matters, but you can do that

**Comment by Kalpesh-18** [comment]
I have added that, will the build get auto triggered now, or I have to commit again. But anyways I guess that's not the part we are validating.

**Comment by 7ubi** [comment]
No it's not I just have to give my approval then i can merge it

**Review by 7ubi — APPROVED** [review]
This looks good to me. Thanks for making it!

**Comment by Kalpesh-18** [comment]
Please consider including the Docker commands in the README file to make things simpler for users. Thank you. A lot was learned from this. ✌️🏻

**Comment by 7ubi** [comment]
Yes I will do that

**Pull request merged**
